### ISSUE TITLE
BaseFetchException field _exception

### ISSUE THREAD

**Issue by Quurks** [crawler-commons/crawler-commons#105]
Is there any reason for the BaseFetchException._exception field? It just seems to be unnecessary, everything its used for should be possible using the superclass

**Comment by kkrugler** [comment]
It's been a while, but from what I remember, the issue is that the superclass "cause" field creates issues when trying to use Hadoop Writable to serialize/deserialize. Not sure if it's because "cause" by default points to the exception itself ("this"), and when we're running with Kryo serialization (e.g. in Cascading local mode) this causes an endless loop...

**Comment by Quurks** [comment]
It seems strange to me hadoop would have problems with something as simple as a normal exception. 

The _exception field exists since class creation, https://github.com/crawler-commons/crawler-commons/commit/cd55b6b92eeb12bf92400a6d82cc2194f831cbe7, and kryo shouldnt have problems with serializing cycles https://github.com/EsotericSoftware/kryo#references

**Comment by jnioche** [comment]
@Quurks please note that the fetcher related code is deprecated and will be removed from future version
see #92
