### ISSUE TITLE
<sitemapindex> not being processed

### ISSUE THREAD

**Issue by lewismc** [crawler-commons/crawler-commons#168]
I recently ended up attempting to process the sitemap located at https://www.autotrader.com/sitemap.xml
As you can see, the XML represents a sitemapindex as follows...
```
<sitemapindex>
  <sitemap>
    <loc>https://www.autotrader.com/sitemap_main.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.autotrader.com/sitemap_srp_index_all.xml</loc>
  </sitemap>
...
```
It is my understanding that we do currently support [sitemap index files](https://www.sitemaps.org/protocol.html#index)... how this particular file seems to presenting problems for me.

**Comment by sebastian-nagel** [comment]
@lewismc: afaics, it works for both the DOM and SAX parser:
```
java ... [-Dsitemap.useSax=true] crawlercommons.sitemaps.SiteMapTester https://www.autotrader.com/sitemap.xml
```
However, there are many URLs and it takes horribly long: jstack shows that most of the time is used reading data from a socket and converting it into a byte array.

**Comment by lewismc** [comment]
OK this is good news. I was attempting to use CC 0.7 so maybe this is the issue as well... I will suggest that we update CC in the patch at https://github.com/apache/nutch/pull/195 then report back here.

**Comment by sebastian-nagel** [comment]
It could be also that we need a special treatment (the processing is still running - 45 min. and 300,000 URLs now). Btw., it took me longer to make CC's [SitemapInjector](https://github.com/commoncrawl/nutch/blob/cc/src/java/org/apache/nutch/crawl/SitemapInjector.java) robust against any timeouts and overlong URL lists (theoretically a sitemap index is allowed to provide 2.5 billion URLs). Looks like the autotrader sitemap index is [nested](https://webmasters.stackexchange.com/questions/18243/can-a-sitemap-index-contain-other-sitemap-indexes) (the index contains links to other indexes). Good questions whether this should be accepted.

**Comment by sebastian-nagel** [comment]
Hi @lewismc, I've finally downloaded all the sitemaps referenced from https://www.autotrader.com/sitemap.xml: it took 1h 17m from a server with good internet connection. Just to confirm: parsing with crawler-commons succeeds, the problem is probably caused by the long fetch time or the long list of URLs (> 3 million). That's another good point: fetching 3 million URLs from on host with a polite delay will take weeks, so it's recommended to drop or sample URLs. For testing (see [sitemap-performance-test](https://github.com/sebastian-nagel/sitemap-performance-test/)) I've put the archived sitemaps to s3://commoncrawl-seeds/sitemaps/test/sitemap-test-autotrader-com-2017-07-05.warc.gz. Parsing is fast: 16s using SAX, 23 using DOM parser.

**Comment by lewismc** [comment]
Thanks for looking into this Seb I appreciate it. Looks like we can close this issue off... it looks like the error may be on the Nutch side. I'll take it back to Markus and see what we can derive.
