### ISSUE TITLE
[BasicNormalizer] Trailing question mark in url query test should be added

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#247]
Currently our normalizer doesn't remove a trailing question mark - I think it should. [As @sebastian-nagel writes in this thread, the trailing question mark is the expected behaviour]

Example: http://shekhargulati.com?

The above example was taken from [UrlCleaner](https://github.com/shekhargulati/urlcleaner/blob/master/src/test/java/com/shekhargulati/urlcleaner/UrlCleanerSpec.java), test name: shouldRemoveQuestionMarkWhenThereIsNoQueryParameter()

**Comment by sebastian-nagel** [comment]
Firefox and Chromium transform it to "https://shekhargulati.com/?". That's also the (current) behavior of BasicURLNormalizer. It appears that "the exact structure of the query string is not standardized" ([Wikipedia Query string](https://en.wikipedia.org/wiki/Query_string)). In doubt, the web framework (servlet, CGI, etc.) may handle the cases differently, whether the query is empty or there is none ("null"). In any case, would be good to have a test unit to test the expected behavior.

**Comment by Chaiavi** [comment]
Ok, so it seems best to leave the current behaviour, just add a test case to make sure this behaviour stays (Like Chromium & Firefox).

I will leave this one open, and change the title to make more sense

**Comment by sebastian-nagel** [comment]
Sorry, my fault: should verify that unit tests are really executed (see #273). The real current behavior is that `http://example.com?` isn't normalized as expected. Needs to be fixed.
