### ISSUE TITLE
[BasicNormalizer] Convert Unicode IDNs to Punycode

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#248]
Should we normalize this:
http://xn--xample-hva.com

To this:
http://êxample.com
?

Currently we don't

Which fails the [UrlCleaner](https://github.com/shekhargulati/urlcleaner/blob/master/src/test/java/com/shekhargulati/urlcleaner/UrlCleanerSpec.java) test: shouldConvertPunnycodeHostToUnicode

**Comment by sebastian-nagel** [comment]
Maybe the other way around? Convert everything to Punycode because
- we also normalize all Unicode characters in the path and query parts (here using percent encoding)
- latest if you want to fetch the URL you need to transform the host part to ASCII. Having this already done is more efficient and also prevents from errors when you do not expect them (eg. #231)

**Comment by Chaiavi** [comment]
I agree, it makes more sense better to convert to punycode

**Comment by sebastian-nagel** [comment]
See [NUTCH-2746](https://issues.apache.org/jira/browse/NUTCH-2746) / apache/nutch#480 - I'll transfer it to crawler-commons.
