### ISSUE TITLE
org.xml.sax.SAXParseException; lineNumber: 1592; columnNumber: 2; XML document structures must start and end within the same entity.

### ISSUE THREAD

**Issue by utsw-zhu** [crawler-commons/crawler-commons#310]
I have sitemap file which has 6000 urls and 1MB size. The max urls and size both meet teh requirement. But It always gives the error like: org.xml.sax.SAXParseException; lineNumber: 1592; columnNumber: 2; XML document structures must start and end within the same entity. Even I removed entry at line 1592, it still gives the same error at the same line number. I checked the entry. Nothing is wrong. It looks well formatted. It can't be wrong because it was generated by java application. But if I remove those lines after line 1592, everything works fine. It sounds that it only allows to process less than 1592 lines but clearly it allows 50000 urls (which means that it should more than 1592 lines). I am totally confused.

**Comment by utsw-zhu** [comment]
Issue resolved

**Comment by sebastian-nagel** [comment]
Hi @utsw-zhu, the SitemapParser has a option [allowPartial](https://github.com/crawler-commons/crawler-commons/blob/9630f4c09cf03af90c965e19431134539ff6ba17/src/main/java/crawlercommons/sitemaps/SiteMapParser.java#L125) (set in the constructor) - if a sitemap is truncated or otherwise broken, it will still emit the URLs found so far.
