### ISSUE TITLE
Port existing top-level readme to MarkDown for GitHub

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/crawler-commons#69]
See https://code.google.com/p/crawler-commons/

 - The links to code should be fixed up to ref GitHub files.
 - For now Javadoc links can continue to link to Google code hosting, but that will need to be fixed.

**Comment by Chaiavi** [comment]
I have imported and converted the main page to MarkDown.
I have changed several links to point to GitHub instead of GoogleCode. (Not the JavaDoc links)

For now, I am pointing all releases of CHANGES.TXT to the latest at Master, as we don't have the code of the last releases, and actually the CHANGES.TXT file does contain all changes of all releases, so it seems like a good compromise for now...



The only thing missing now is the JavaDoc links (to the JavaDocs of the previous releases)

**Comment by kkrugler** [comment]
Closing as complete (I added the note about fixing the JavaDoc link on issue #70)
