### ISSUE TITLE
Sitemap doesn't work with uppercase letters in URL anymore (since 0.6)

### ISSUE THREAD

**Issue by lbeuster** [crawler-commons/crawler-commons#90]
If I have uppercase letters the method SiteMapParser.urlIsLegal() returns wrong result because lowercase() is only used for testUrl.

It worked with version 0.5 because also the SiteMap.baseUrl was lowercase, so both urls were lowercase.

Best regards
Lars

**Comment by Chaiavi** [comment]
This is an issue I fixed in the past.

I will look into it

**Comment by Chaiavi** [comment]
Yes.

This issue was found and fixed here:
https://github.com/crawler-commons/crawler-commons/commit/5cf62ab7d5437d8cc4ab56e35a99d2b74e03f62f#diff-e0dd11cacc1f2ecf8f25f3402b9b95e4L628

The original bug was to put in both places the toLowerCase(), as domains might have parts which are case sensitive.


It is currently in a pull request, I will ping the members for someone to have a look and hopefully confirm and merge.


Thanks Lars

**Comment by lbeuster** [comment]
Thanks, I only tried out the master to see if it was already fixed there ;)

**Comment by jnioche** [comment]
@lbeuster has the issue been fixed? can it be closed?
